[package]
name = "tlsinspect"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
rustls = "0.22"
tokio = { version = "1.48.0", features = ["full"] }
tokio-rustls = "0.25"
webpki-roots = "0.26"
x509-parser = "0.16"
